### ISSUE TITLE
TRANS7, TRANSTV, RCTI, MNC

### ISSUE THREAD

**Issue by HexSorcerer** [zafratambores/iptvid#1]
Lapor bang, daftar list diatas tewas

**Comment by zafratambores** [comment]
Done

**Comment by HexSorcerer** [comment]
makasih bang

**Comment by zafratambores** [comment]
sama sama

**Comment by HexSorcerer** [comment]
> sama sama

lapor bang, tvone ikutan mokad ternyata

**Comment by zafratambores** [comment]
coba di muat ulang, barusan ta cek aman di app M3U.

**Comment by HexSorcerer** [comment]
wah iya.. sekali lagi makasih gan.. sukses terus
